# Generated by Django 3.2.13 on 2022-05-12 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_alter_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_of_booking',
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='auth.user'),
        ),
    ]
