# Generated by Django 3.2.13 on 2022-05-12 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_of_booking',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
